FROM jenkinsci/blueocean:latest
#COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
COPY plugins/* /var/jenkins_home/plugins/
#RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt
