FROM phusion/baseimage:master


ENV JAVA_HOME /usr/lib/jvm/java-8
ENV MAVEN_VERSION 3.3.9
ENV MAVEN_HOME /usr/share/maven
ARG CHROME_DRIVER_VERSION=74.0.3729.6


# JAVA
RUN apt-get -y update
RUN apt install -y openjdk-8-jdk 
